### ISSUE TITLE
librosa.load failed

### ISSUE THREAD

**Issue by adamalexandru4** [Bumaza/Musical-Instrument-Classifier#1]
Hello!

I'm trying to test your code, but I face a problem with librosa.load getting a "Backend exception" when I'm trying to load mp3 files. Do you have any idea, why?

**Comment by Bumaza** [comment]
Hi,
Could you show me your log? Thanks!

**Comment by adamalexandru4** [comment]
> C:\Python38\lib\site-packages\librosa\core\audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')
Traceback (most recent call last):
  File "D:/ANUL 4/Semestrul 2/Sisteme biometrice/Toma/Proiect/Musical-Instrument-Classifier-master/classifier.py", line 175, in <module>
    main()
  File "D:/ANUL 4/Semestrul 2/Sisteme biometrice/Toma/Proiect/Musical-Instrument-Classifier-master/classifier.py", line 118, in main
    data = np.array(feature_extraction())
  File "D:/ANUL 4/Semestrul 2/Sisteme biometrice/Toma/Proiect/Musical-Instrument-Classifier-master/classifier.py", line 91, in feature_extraction
    plt.yticks(np.arange(0, max(instruments_counts), max(instruments_counts) // 10))
ZeroDivisionError: division by zero


The traceback shows these errors because the librosa.load fails for every file giving exception for each.

**Comment by Bumaza** [comment]
Do you have set the right path to your music files?  Do you see in debugging a files list? Is it correct?  
Sorry, I can't do anything for you. It works well for me. I don't know what it's wrong.

**Comment by adamalexandru4** [comment]
Yes, I ceated in the project folder the following directories "./data/data/<music_instrument>" and added in the music-instrument folder mp3. I see 5000+ elements in the files list with path "./data/data\\violin\\file_name.mp3".

**Comment by Bumaza** [comment]
Why do you have a Backslash in your path? It doesn't look alright. 
I execute the code on the unix-based system. So just try to modify path like replace all backslashes with slashes remove leading dot and slash and so on.
